export const GET_GLOBAL_INFO = 'GET_GLOBAL_INFO';
export const GET_COUNTRIES_INFO = 'GET_COUNTRIES_INFO';
export const SET_COUNTRY_TO_OBSERVE = 'SET_COUNTRY_TO_OBSERVE';
export const UNSET_COUNTRY_TO_OBSERVE = 'UNSET_COUNTRY_TO_OBSERVE';
export const SET_COUNTRY_REGIONS_INFO = 'SET_COUNTRY_REGIONS_INFO';
export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT';
