export const GET_GLOBAL_INFO = 'GET_GLOBAL_INFO';
export const GET_COUNTRY_INFO = 'GET_COUNTRY_INFO';
export const SET_COUNTRY_TO_OBSERVE = 'SET_COUNTRY_TO_OBSERVE';
export const UNSET_COUNTRY_TO_OBSERVE = 'UNSET_COUNTRY_TO_OBSERVE';
